
// Reports
function reportPdfUrl(id){ return `${API}/api/reports/${id}/pdf`; }
function reportHtmlUrl(id){ return `${API}/api/reports/${id}/html`; }


// ---------- Report Modal ----------
function openReport(id){
  const r=DB.scans.find(s=>s.id===id); if(!r) return;
  document.getElementById('report-modal').classList.remove('hidden');
  renderResult(r, document.getElementById('report-body'));
}
function closeReport(){ document.getElementById('report-modal').classList.add('hidden'); }


// ---------- Report Export ----------
function reportHTML(r){
  return `<html><head><meta charset="utf-8"><title>CyberInspect Report – ${r.url}</title>
    <style>
      body{font-family:'Segoe UI',Arial,sans-serif;padding:40px;color:#0a1330;background:#f4f8fb;max-width:900px;margin:auto}
      h1{color:#00a3b5}h2{margin-top:26px;color:#0d1f4c}
      .head{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #22e6e6;padding-bottom:16px}
      .badge{padding:6px 16px;border-radius:20px;background:#e0fafa;color:#008a99;font-weight:700}
      .score{font-size:44px;font-weight:800;color:#0d1f4c}
      table{border-collapse:collapse;width:100%;margin:10px 0;background:#fff;border-radius:8px;overflow:hidden}
      td,th{border-bottom:1px solid #e4ebf5;padding:11px 14px;text-align:left;font-size:14px}
      th{background:#0d1f4c;color:#fff}
      .ok{color:#16a34a;font-weight:600}.bad{color:#dc2626;font-weight:600}
      .foot{margin-top:30px;font-size:12px;color:#8a9bc4;border-top:1px solid #e4ebf5;padding-top:14px}
    </style></head><body>
    <div class="head"><h1>🛡️ CyberInspect Security Report</h1>
      <div style="text-align:right"><div class="score">${r.score}<span style="font-size:18px;color:#8a9bc4">/100</span></div>
      <span class="badge">${r.risk} Risk</span></div></div>
    <p><b>Website:</b> ${r.fullUrl}<br><b>Scanned:</b> ${new Date(r.date).toLocaleString()}</p>

    <h2>🔒 SSL/TLS</h2><table>
      <tr><td>HTTPS Available</td><td class="${r.ssl.https?'ok':'bad'}">${r.ssl.https?'Yes':'No'}</td></tr>
      <tr><td>Certificate Valid</td><td class="${r.ssl.valid?'ok':'bad'}">${r.ssl.valid?'Yes':'No'}</td></tr>
      <tr><td>Issuer</td><td>${r.ssl.issuer}</td></tr>
      <tr><td>Expires</td><td>${r.ssl.expires} (${r.ssl.daysToExpiry} days)</td></tr>
      <tr><td>TLS Versions</td><td>${r.ssl.tls.join(', ')}</td></tr></table>

    <h2>🛡️ Security Headers</h2><table>${r.headers.map(h=>`<tr><td>${h.name}</td>
      <td class="${h.present?'ok':'bad'}">${h.present?'Present':'Missing'}</td></tr>`).join('')}</table>

    <h2>🌍 Domain</h2><table>
      <tr><td>Registrar</td><td>${r.domain.registrar}</td></tr>
      <tr><td>Domain Age</td><td>${r.domain.age}</td></tr>
      <tr><td>Expires</td><td>${r.domain.expires}</td></tr>
      <tr><td>IP Address</td><td>${r.domain.ip}</td></tr>
      <tr><td>Hosting</td><td>${r.domain.host}</td></tr></table>

    <h2>🌐 DNS</h2><table>
      <tr><td>A</td><td>${r.dns.A}</td></tr><tr><td>AAAA</td><td>${r.dns.AAAA}</td></tr>
      <tr><td>MX</td><td>${r.dns.MX}</td></tr><tr><td>NS</td><td>${r.dns.NS}</td></tr>
      <tr><td>SPF</td><td class="${r.dns.SPF?'ok':'bad'}">${r.dns.SPF?'Configured':'Missing'}</td></tr>
      <tr><td>DMARC</td><td class="${r.dns.DMARC?'ok':'bad'}">${r.dns.DMARC?'Configured':'Missing'}</td></tr>
      <tr><td>DKIM</td><td class="${r.dns.DKIM?'ok':'bad'}">${r.dns.DKIM?'Detected':'Not detected'}</td></tr></table>

    <h2>🚨 Reputation</h2><table>
      <tr><td>Blacklist</td><td class="${r.rep.blacklisted?'bad':'ok'}">${r.rep.blacklisted?'Listed':'Clean'}</td></tr>
      <tr><td>Phishing</td><td class="${r.rep.phishing?'bad':'ok'}">${r.rep.phishing?'Reported':'None'}</td></tr>
      <tr><td>Malware</td><td class="${r.rep.malware?'bad':'ok'}">${r.rep.malware?'Reported':'None'}</td></tr>
      <tr><td>Summary</td><td>${r.rep.summary}</td></tr></table>

    <h2>🍪 Cookies</h2><table>
      <tr><td>Secure</td><td class="${r.cookies.secure?'ok':'bad'}">${r.cookies.secure?'Yes':'No'}</td></tr>
      <tr><td>HttpOnly</td><td class="${r.cookies.httpOnly?'ok':'bad'}">${r.cookies.httpOnly?'Yes':'No'}</td></tr>
      <tr><td>SameSite</td><td class="${r.cookies.sameSite?'ok':'bad'}">${r.cookies.sameSite?'Yes':'No'}</td></tr></table>

    <h2>🔍 Technology</h2><table>
      <tr><td>Web Server</td><td>${r.tech.server}</td></tr>
      <tr><td>CMS</td><td>${r.tech.cms}</td></tr>
      <tr><td>JS Frameworks</td><td>${r.tech.js.join(', ')}</td></tr>
      <tr><td>CDN</td><td>${r.tech.cdn}</td></tr>
      <tr><td>Reverse Proxy</td><td>${r.tech.proxy}</td></tr></table>

    <div class="foot">Generated by CyberInspect on ${new Date().toLocaleString()}.
    Assessment based on observable technical indicators only and does not guarantee complete safety.
    Scan only websites you own or are authorized to assess.</div>
    </body></html>`;
}
function downloadHTML(id){
  const r=DB.scans.find(s=>s.id===id);
  const blob=new Blob([reportHTML(r)],{type:'text/html'});
  const a=document.createElement('a'); a.href=URL.createObjectURL(blob);
  a.download=`CyberInspect_${r.url}_${Date.now()}.html`; a.click();
  toast('HTML report downloaded.','success');
}
function downloadPDF(id){
  const r=DB.scans.find(s=>s.id===id);
  const w=window.open('','_blank');
  w.document.write(reportHTML(r));
  w.document.close(); setTimeout(()=>w.print(),450);
  toast('Opening print dialog — choose "Save as PDF".','info');
}

// ---------- Exports ----------
window.renderReports = renderReports;
window.openReport = openReport;
window.closeReport = closeReport;
window.downloadHTML = downloadHTML;
window.downloadPDF = downloadPDF;